dist: trusty
#ttt
language: d

d:
  - dmd
  - dmd-beta
  #- gdc is disabled, waiting for std.experimental.logger
  - ldc
  - ldc-beta

addons:
  apt:
    packages:
      - libevent-dev

  postgresql: 9.6

services: postgresql

env:
  - CONN_STRING="dbname=vibe-test"

before_script:
  - psql -c 'create database "vibe-test"' -U postgres

script:
  - dub test
  - dub run --config=integration_test -- --conninfo="${CONN_STRING}" --debug=true
  - dub run --config=integration_test_vibe_core -- --conninfo="${CONN_STRING}" --debug=true
  - dub build :example

matrix:
  include:
    - d: dmd

      script:
        - dub build --build=ddox

      cache: { directories: [$HOME/.dub] }

      deploy:
        provider: pages
        skip_cleanup: true
        keep-history: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
